[package]
name = "metassr"
version = "0.0.1-alpha"
edition = "2021"
description = "Another SSR framework but built with MetaCall!"
license = "MIT"
license-file = "LICENSE"
default-run = "metassr"


[package.metadata]
authors = ["Mohamed Emad (hulxxv@gmail.com)"]

[dependencies]
anyhow = "1.0.82"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
metacall = "0.4.1"
nu-ansi-term = "0.50.0"
walkdir = "2.5.0"
serde_json = "1.0.120"
lazy_static = "1.5.0"

axum = "0.7.5"
tokio = { version = "1.36.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["trace", "fs"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "env-filter"] }

logger = { path = "crates/logger" }
metassr-server = { path = "crates/metassr-server" }
metassr-build = { path = "crates/metassr-build" }
metassr-utils = { path = "crates/metassr-utils" }
html-generator = { path = "crates/html-generator" }
serde = "1.0.207"
tower-layer = "0.3.3"
tower-service = "0.3.3"
metassr-create = { path = "crates/metassr-create" }
metassr-bundler = { path = "crates/metassr-bundler" }
metassr-fs-analyzer = { path = "crates/metassr-fs-analyzer" }

[workspace]
members = [
    "crates/logger",
    "crates/metassr-build",
    "crates/metassr-server",
    "crates/metassr-utils",
    "crates/html-generator",
    "metassr-cli",
    "crates/metassr-create",
    "crates/metassr-bundler",
    "crates/metassr-fs-analyzer", "crates/metassr-hooks",
]

[[bin]]
name = "metassr"
path = "metassr-cli/src/main.rs"
