[package]
name = "metassr-build"
version = "0.1.0"
edition = "2021"
description = "Web builder & bundler built on Rspack and built for MetaSSR."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
